<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1718830928552' stop='1718830977771'>
    <name>Add To Cart an Apple Product</name>
    <title>Add To Cart an Apple Product</title>
    <test-cases>
        <test-case start='1718830928552' status='failed' stop='1718830977769'>
            <name>TC01: User can Add an item to Cart</name>
            <title>TC01: User can Add an item to Cart</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Timed out retrying after 4000ms: expected 'https://ecommerce-playground.lambdatest.io/index.php?route=checkout/checkout' to include 'checkout/confirm'</message>
                <stack-trace>AssertionError: Timed out retrying after 4000ms: expected 'https://ecommerce-playground.lambdatest.io/index.php?route=checkout/checkout' to include 'checkout/confirm'
                    at CheckoutClass.ConfirmOrderurl (webpack://seekatest/./cypress/e2e/Pages/CheckoutPage.js:60:17)
                    at Context.eval (webpack://seekatest/./cypress/e2e/Test/AddToCart.cy.js:38:21)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>